package com.example.entity;

import java.util.Date;

public class TblAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.admin_id
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    private String adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.password
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.admin_family_name
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    private String adminFamilyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.admin_first_name
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    private String adminFirstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.REGIST_ID
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    private String registId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.REGIST_DATE
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.UPDATE_ID
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.UPDATE_DATE
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.DELETE_FLG
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    private String deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.admin_id
     *
     * @return the value of tbl_admin.admin_id
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.admin_id
     *
     * @param adminId the value for tbl_admin.admin_id
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.password
     *
     * @return the value of tbl_admin.password
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.password
     *
     * @param password the value for tbl_admin.password
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.admin_family_name
     *
     * @return the value of tbl_admin.admin_family_name
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public String getAdminFamilyName() {
        return adminFamilyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.admin_family_name
     *
     * @param adminFamilyName the value for tbl_admin.admin_family_name
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public void setAdminFamilyName(String adminFamilyName) {
        this.adminFamilyName = adminFamilyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.admin_first_name
     *
     * @return the value of tbl_admin.admin_first_name
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public String getAdminFirstName() {
        return adminFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.admin_first_name
     *
     * @param adminFirstName the value for tbl_admin.admin_first_name
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public void setAdminFirstName(String adminFirstName) {
        this.adminFirstName = adminFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.REGIST_ID
     *
     * @return the value of tbl_admin.REGIST_ID
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public String getRegistId() {
        return registId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.REGIST_ID
     *
     * @param registId the value for tbl_admin.REGIST_ID
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public void setRegistId(String registId) {
        this.registId = registId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.REGIST_DATE
     *
     * @return the value of tbl_admin.REGIST_DATE
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.REGIST_DATE
     *
     * @param registDate the value for tbl_admin.REGIST_DATE
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.UPDATE_ID
     *
     * @return the value of tbl_admin.UPDATE_ID
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.UPDATE_ID
     *
     * @param updateId the value for tbl_admin.UPDATE_ID
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.UPDATE_DATE
     *
     * @return the value of tbl_admin.UPDATE_DATE
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.UPDATE_DATE
     *
     * @param updateDate the value for tbl_admin.UPDATE_DATE
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.DELETE_FLG
     *
     * @return the value of tbl_admin.DELETE_FLG
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.DELETE_FLG
     *
     * @param deleteFlg the value for tbl_admin.DELETE_FLG
     *
     * @mbg.generated Thu May 07 12:42:38 ICT 2020
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg;
    }
}